#!/bin/sh
# chkconfig: 345 99 10
# 345-means that the service will be started in init levels 3 and 5 and will be stopped in other levels.
# 99-means that the service will be started at the near end of the init level processing
# 10-means that the service will be stopped at the near beginning of the init level processing
# description: Oracle auto start-stop script.
#
# Set ORA_OWNER to the user id of the owner of the
# Oracle database software.

ORA_OWNER=oracle

case "$1" in

    'start')
        # Start the Oracle databases:
        # The following command assumes that the oracle login
        # will not prompt the user for any values
        # Remove "&" if you don't want startup as a background process.
        su $ORA_OWNER -c "/home/oracle/scripts/start_db.sh >> /home/oracle/scripts/startup_shutdown.log 2>&1" &
        touch /var/lock/subsys/dbora
        ;;

    'stop')
        # Stop the Oracle databases:
        # The following command assumes that the oracle login
        # will not prompt the user for any values
        su $ORA_OWNER -c "/home/oracle/scripts/stop_db.sh >> /home/oracle/scripts/startup_shutdown.log 2>&1"
        rm -f /var/lock/subsys/dbora
        ;;

esac